In [47]:
from sklearn.datasets import fetch_20newsgroups

twenty_train = fetch_20newsgroups(subset='all',shuffle=True, random_state=42)

In [48]:
newsgroups=twenty_train

In [49]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(newsgroups.data)

In [50]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity_result = cosine_similarity(vectors)

In [53]:
from sklearn.metrics.pairwise import euclidean_distances
euclidean_distances_result = euclidean_distances(vectors)

In [44]:
print(euclidean_distances_result)

[[0.         1.38640872 1.33914378 ... 1.38528237 1.38873026 1.3634162 ]
 [1.38640872 0.         1.38881743 ... 1.4047104  1.39333391 1.38272563]
 [1.33914378 1.38881743 0.         ... 1.36707034 1.37511363 1.3342936 ]
 ...
 [1.38528237 1.4047104  1.36707034 ... 0.         1.39333323 1.35169863]
 [1.38873026 1.39333391 1.37511363 ... 1.39333323 0.         1.37341324]
 [1.3634162  1.38272563 1.3342936  ... 1.35169863 1.37341324 0.        ]]


In [ ]:
#################20 NG KNN###############

In [3]:
from sklearn.datasets import fetch_20newsgroups
train_20newsgroups = fetch_20newsgroups(subset='train',shuffle=True, random_state=42)
test_20newsgroups =  fetch_20newsgroups(subset='test',shuffle=True, random_state=42)

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer()
vectors_train_20newsgroups = vectorizer.fit_transform(train_20newsgroups.data)
vocab = vectorizer.get_feature_names()
vectorizer2=TfidfVectorizer(vocabulary=vocab)
vectors_test_20newsgroups = vectorizer2.fit_transform(test_20newsgroups.data)
similarity_20news = cosine_similarity(vectors_test_20newsgroups,vectors_train_20newsgroups)

In [26]:
### iterate through  esultant similarity_20news matrix and fetch the top most target
from collections import Counter
from sklearn.metrics import accuracy_score
import numpy

k=5

predictions = []
for i in range(vectors_test_20newsgroups.shape[0]):
    neighbors = []
    targets = []
    neighbors = numpy.argsort(-similarity_20news[i])
    for p in range(k):
        index = neighbors[p]
        targets.append(train_20newsgroups.target[index])
    predictions.append(Counter(targets).most_common(1)[0][0])
print(len(predictions))
print(accuracy_score(test_20newsgroups.target,numpy.asarray(predictions))*100)    

7532
67.57833244822092


In [25]:
def find_k_nearest_neighbours(idx, k, similarity_matrix):
    t=[]
    neighbhors_idx = numpy.argsort(-similarity_matrix[idx])
    for p in range(k):
        index = neighbhors_idx[p]
        #print(neighbhors_idx[p])
        t.append(train_20newsgroups.target_names[train_20newsgroups.target[index]])
        #print(Counter(t))
        print(train_20newsgroups.target_names[train_20newsgroups.target[index]])
    
        
        
        

In [35]:
print(train_20newsgroups.target_names[train_20newsgroups.target[990]])

comp.sys.mac.hardware


In [34]:
find_k_nearest_neighbours(990,5,similarity_20news)

comp.sys.mac.hardware
comp.sys.mac.hardware
comp.sys.mac.hardware
comp.sys.mac.hardware
comp.sys.mac.hardware


In [12]:
from sklearn.metrics.pairwise import euclidean_distances
similarity_ED = euclidean_distances(vectors_test_20newsgroups,vectors_train_20newsgroups)

In [14]:
#### KNN on euclidean distance
from collections import Counter
from sklearn.metrics import accuracy_score
k=5

predictions = []
for i in range(vectors_test_20newsgroups.shape[0]):
    neighbors = []
    targets = []
    neighbors = numpy.argsort(similarity_ED[i])
    for p in range(k):
        index = neighbors[p]
        targets.append(train_20newsgroups.target[index])
    predictions.append(Counter(targets).most_common(1)[0][0])
print(accuracy_score(test_20newsgroups.target,numpy.asarray(predictions))*100) 

67.57833244822092


In [255]:
similarity_ED

array([[1.35178943, 1.39016632, 1.31811783, ..., 1.3819702 , 1.37789075,
        1.4009934 ],
       [1.38789265, 1.39415195, 1.36577181, ..., 1.40198461, 1.38900802,
        1.38983053],
       [1.40059203, 1.40401556, 1.38305367, ..., 1.39892692, 1.38630761,
        1.40881364],
       ...,
       [1.34709366, 1.38388594, 1.33565396, ..., 1.37566362, 1.37389282,
        1.39386309],
       [1.37483722, 1.37010077, 1.37004049, ..., 1.3990198 , 1.38832833,
        1.40300334],
       [1.3672942 , 1.39765285, 1.35397851, ..., 1.38420384, 1.35585538,
        1.40775005]])

In [61]:
#cosine similarity shape for problem 3
cosine_similarity_result.shape

(18846, 18846)

In [66]:
#cosine similarity shape for problem 4
print("test set shape")
print(vectors_test_20newsgroups.shape)
print("train set shape")
print(vectors_train_20newsgroups.shape)
print("similarity matrix test x train")
print(similarity_20news.shape)

test set shape
(7532, 130107)
train set shape
(11314, 130107)
similarity matrix test x train
(7532, 11314)


In [51]:
import numpy as np
np.savetxt('consine_mat_20NG', cosine_similarity_result, delimiter=',')

In [54]:
np.savetxt('ED_prob3_20NG', euclidean_distances_result, delimiter=',')

In [55]:
np.savetxt('consine_prob3_20NG', similarity_20news, delimiter=',')