In [74]:
#load the file
import numpy as np
import math
from scipy.stats import multivariate_normal
import time

In [75]:
x_2=np.loadtxt("2gaussian.txt")

In [76]:
print(get_random_mu(2,x_2))

[array([[7.4534999, 5.1527374]]), array([[2.50384702, 0.95281252]])]


In [77]:
def get_random_mu(k,x):
    mu=[]
    for i in range(0, k):
        mu.append(x[np.random.randint(0, x.shape[0], size=1)])  
    #print(mu)
    return mu

In [78]:
def generate_covariance(k):
    cov = []
    for i in range(k):
        cov.append(np.identity(2))
    return cov

In [79]:
def EM(k,x,max_iterations):
    ###Initialization
    tol=0.001
    mu = get_random_mu(k,x)
    print("initial mu:",mu)
    if k == 2:
        cov = [np.identity(2),np.identity(2)]
    else:
        cov = [np.identity(2),np.identity(2),np.identity(2)]
    print("initial cov:",cov)
    N,d = x.shape
    w=[1./k]*k
    print("initial weights:",w)
    converged=False
    ll_old=0
    ll_new=0
    for iteration in range(max_iterations):
        
        ##The E step
        expectation = np.zeros((N, k))
        print("performing expectation for iteration:"+str(iteration))                       
        for i in range(0,N):
            for m in range(0,k):
                e_val=multivariate_normal.pdf(x[i], mean=mu[m][0], cov=cov[m])
                expectation[i][m]=w[m]*e_val
                 
            expectation[i] /=expectation[i].sum(0)
            
#         print (expectation)
        old_mu = mu
        old_cov = cov
        old_w = w
        
        print("old mu:",old_mu)
        print("old_cov:",old_cov)
        print("old_w:",old_w)
        
        mu = []
        cov = []
        w = []
        ##The M step
        print("performing maximization for iteration:"+str(iteration))                       
        for m in range(0,k):
            
            num_cov = 0.0
            num_mean = 0.0 
            expectation_sum = 0.0
            
            for i in range(0,N):
                
                temp = np.array(x[i]-old_mu[m])
                e=expectation[i][m]
                
                num_cov += e*np.matmul(temp.T,temp) 
                #print("intermediate cov:",num_cov)
                num_mean += e*x[i]
                expectation_sum+=e
            
            num_mean = [num_mean]
            cov.append(num_cov/expectation_sum)
            mu.append(num_mean/expectation_sum)
            w.append(expectation_sum/N)
            
        print("new mu:",mu)
        print("new_cov:",cov)
        print("old_w:",w)
        
        flag=False
        ll_new=0.0
        for i in range(N):
            for j in range(k):
                ll_new += math.log(expectation[i][j])
              
        if np.abs(ll_new-ll_old)<tol:
            print (ll_new,ll_old)
            break
            
        print("ll_old:"+str(ll_old))
        print("ll_new:"+str(ll_new)) 
        ll_old=ll_new     
         

        iteration+=1
    #print("ll_old:"+str(ll_old))
    #print("ll_new:"+str(ll_new))
    print("iteration:",iteration)
    print("results")
    for i in range(k):
        print("mu["+str(i)+"]:",mu[i])
        print("cov["+str(i)+"]:",cov[i])
        

        
        

            
            
       
    
    
    


In [80]:
print("2 guassian")
start = time.time()
EM(2,x_2,50)
end = time.time()
print("Time taken:"+str(end - start)+" seconds")


2 guassian
initial mu: [array([[3.26017622, 3.3028496 ]]), array([[8.72969572, 3.47220176]])]
initial cov: [array([[1., 0.],
       [0., 1.]]), array([[1., 0.],
       [0., 1.]])]
initial weights: [0.5, 0.5]
performing expectation for iteration:0
old mu: [array([[3.26017622, 3.3028496 ]]), array([[8.72969572, 3.47220176]])]
old_cov: [array([[1., 0.],
       [0., 1.]]), array([[1., 0.],
       [0., 1.]])]
old_w: [0.5, 0.5]
performing maximization for iteration:0
new mu: [array([[3.61897535, 3.08968653]]), array([[7.28703388, 4.13129198]])]
new_cov: [array([[2.18822246, 0.05086818],
       [0.05086818, 2.47196067]]), array([[ 2.72057052, -0.63742314],
       [-0.63742314,  1.33638449]])]
old_w: [0.4414965739199418, 0.5585034260800579]
ll_old:0
ll_new:-59775.25036903673
performing expectation for iteration:1
old mu: [array([[3.61897535, 3.08968653]]), array([[7.28703388, 4.13129198]])]
old_cov: [array([[2.18822246, 0.05086818],
       [0.05086818, 2.47196067]]), array([[ 2.72057052, -0.63

old mu: [array([[3.0108261 , 3.05034985]]), array([[7.02157352, 3.98794708]])]
old_cov: [array([[1.03843012, 0.02458078],
       [0.02458078, 2.92501208]]), array([[0.96040631, 0.48934027],
       [0.48934027, 0.99418225]])]
old_w: [0.3375866833790202, 0.6624133166209789]
performing maximization for iteration:12
new mu: [array([[3.00543077, 3.05086445]]), array([[7.01890237, 3.98642122]])]
new_cov: [array([[1.0291872 , 0.02533997],
       [0.02533997, 2.92911925]]), array([[0.96488565, 0.49187442],
       [0.49187442, 0.99637231]])]
old_w: [0.33669199723703547, 0.6633080027629634]
ll_old:-54745.16563443288
ll_new:-55125.72629201491
performing expectation for iteration:13
old mu: [array([[3.00543077, 3.05086445]]), array([[7.01890237, 3.98642122]])]
old_cov: [array([[1.0291872 , 0.02533997],
       [0.02533997, 2.92911925]]), array([[0.96488565, 0.49187442],
       [0.49187442, 0.99637231]])]
old_w: [0.33669199723703547, 0.6633080027629634]
performing maximization for iteration:13
new m

ll_old:-55921.28698770842
ll_new:-55924.80667320487
performing expectation for iteration:25
old mu: [array([[2.99423389, 3.05208447]]), array([[7.01320131, 3.98316447]])]
old_cov: [array([[1.01040294, 0.02717301],
       [0.02717301, 2.93774371]]), array([[0.97466657, 0.49741789],
       [0.49741789, 1.00109831]])]
old_w: [0.33481304210684665, 0.665186957893153]
performing maximization for iteration:25
new mu: [array([[2.99420075, 3.05208841]]), array([[7.01318411, 3.98315464]])]
new_cov: [array([[1.01034816, 0.02717898],
       [0.02717898, 2.93776944]]), array([[0.97469655, 0.4974349 ],
       [0.4974349 , 1.00111269]])]
old_w: [0.3348074333283761, 0.6651925666716249]
ll_old:-55924.80667320487
ll_new:-55927.18370284997
performing expectation for iteration:26
old mu: [array([[2.99420075, 3.05208841]]), array([[7.01318411, 3.98315464]])]
old_cov: [array([[1.01034816, 0.02717898],
       [0.02717898, 2.93776944]]), array([[0.97469655, 0.4974349 ],
       [0.4974349 , 1.00111269]])]
old_

old mu: [array([[2.99413274, 3.05209649]]), array([[7.01314879, 3.98313446]])]
old_cov: [array([[1.01023576, 0.02719123],
       [0.02719123, 2.93782226]]), array([[0.9747581 , 0.49746984],
       [0.49746984, 1.0011422 ]])]
old_w: [0.33479592139815145, 0.6652040786018482]
performing maximization for iteration:37
new mu: [array([[2.99413244, 3.05209653]]), array([[7.01314863, 3.98313437]])]
new_cov: [array([[1.01023527, 0.02719128],
       [0.02719128, 2.93782249]]), array([[0.97475837, 0.49746999],
       [0.49746999, 1.00114233]])]
old_w: [0.3347958709234809, 0.665204129076518]
ll_old:-55932.06225100753
ll_new:-55932.08364046445
performing expectation for iteration:38
old mu: [array([[2.99413244, 3.05209653]]), array([[7.01314863, 3.98313437]])]
old_cov: [array([[1.01023527, 0.02719128],
       [0.02719128, 2.93782249]]), array([[0.97475837, 0.49746999],
       [0.49746999, 1.00114233]])]
old_w: [0.3347958709234809, 0.665204129076518]
performing maximization for iteration:38
new mu: 

In [60]:
x_3=np.loadtxt("3gaussian.txt")

In [66]:
print("3 guassian")
start = time.time()
EM(3,x_3,120)
end = time.time()
print("Time taken:"+str(end - start)+" seconds")


3 guassian
[array([[6.67914778, 3.09212802]]), array([[3.16680035, 4.05329316]]), array([[4.42043304, 6.87633436]])]
initial mu: [array([[6.67914778, 3.09212802]]), array([[3.16680035, 4.05329316]]), array([[4.42043304, 6.87633436]])]
initial cov: [array([[1., 0.],
       [0., 1.]]), array([[1., 0.],
       [0., 1.]]), array([[1., 0.],
       [0., 1.]])]
initial weights: [0.3333333333333333, 0.3333333333333333, 0.3333333333333333]
performing expectation for iteration:0
old mu: [array([[6.67914778, 3.09212802]]), array([[3.16680035, 4.05329316]]), array([[4.42043304, 6.87633436]])]
old_cov: [array([[1., 0.],
       [0., 1.]]), array([[1., 0.],
       [0., 1.]]), array([[1., 0.],
       [0., 1.]])]
old_w: [0.3333333333333333, 0.3333333333333333, 0.3333333333333333]
performing maximization for iteration:0
new mu: [array([[6.91683134, 3.89815622]]), array([[3.09504113, 3.21842636]]), array([[5.02676253, 7.05890516]])]
new_cov: [array([[1.27052178, 0.92545562],
       [0.92545562, 1.9856304

new mu: [array([[7.0240771 , 4.01756773]]), array([[3.05536398, 3.09293322]]), array([[5.01889061, 7.00857924]])]
new_cov: [array([[0.98590988, 0.49881306],
       [0.49881306, 0.99619922]]), array([[1.04062858, 0.05758531],
       [0.05758531, 3.47572002]]), array([[0.97064693, 0.18018529],
       [0.18018529, 0.96479865]])]
old_w: [0.29819091239272066, 0.20917864063692382, 0.492630446970356]
ll_old:-180573.07428948986
ll_new:-180920.65136206694
performing expectation for iteration:9
old mu: [array([[7.0240771 , 4.01756773]]), array([[3.05536398, 3.09293322]]), array([[5.01889061, 7.00857924]])]
old_cov: [array([[0.98590988, 0.49881306],
       [0.49881306, 0.99619922]]), array([[1.04062858, 0.05758531],
       [0.05758531, 3.47572002]]), array([[0.97064693, 0.18018529],
       [0.18018529, 0.96479865]])]
old_w: [0.29819091239272066, 0.20917864063692382, 0.492630446970356]
performing maximization for iteration:9
new mu: [array([[7.02399791, 4.01723803]]), array([[3.05347829, 3.0877816

new mu: [array([[7.02260012, 4.01603131]]), array([[3.04469255, 3.06273175]]), array([[5.01417645, 7.0036409 ]])]
new_cov: [array([[0.98865493, 0.50028461],
       [0.50028461, 0.9955937 ]]), array([[1.03234933, 0.03624041],
       [0.03624041, 3.4135592 ]]), array([[0.97673295, 0.18332401],
       [0.18332401, 0.97163806]])]
old_w: [0.29830316556565734, 0.2067569167393928, 0.49493991769494794]
ll_old:-181908.9732921024
ll_new:-181963.11579933696
performing expectation for iteration:18
old mu: [array([[7.02260012, 4.01603131]]), array([[3.04469255, 3.06273175]]), array([[5.01417645, 7.0036409 ]])]
old_cov: [array([[0.98865493, 0.50028461],
       [0.50028461, 0.9955937 ]]), array([[1.03234933, 0.03624041],
       [0.03624041, 3.4135592 ]]), array([[0.97673295, 0.18332401],
       [0.18332401, 0.97163806]])]
old_w: [0.29830316556565734, 0.2067569167393928, 0.49493991769494794]
performing maximization for iteration:18
new mu: [array([[7.02247932, 4.01596255]]), array([[3.04409199, 3.0610

new mu: [array([[7.02189437, 4.01564077]]), array([[3.04126041, 3.05293798]]), array([[5.01249355, 7.00215103]])]
new_cov: [array([[0.98984954, 0.5007432 ],
       [0.5007432 , 0.99562536]]), array([[1.02971194, 0.02975416],
       [0.02975416, 3.39367654]]), array([[0.97878192, 0.18457695],
       [0.18457695, 0.97363478]])]
old_w: [0.29839348398925547, 0.20595965236491348, 0.49564686364583294]
ll_old:-182216.5343715889
ll_new:-182233.63553184972
performing expectation for iteration:27
old mu: [array([[7.02189437, 4.01564077]]), array([[3.04126041, 3.05293798]]), array([[5.01249355, 7.00215103]])]
old_cov: [array([[0.98984954, 0.5007432 ],
       [0.5007432 , 0.99562536]]), array([[1.02971194, 0.02975416],
       [0.02975416, 3.39367654]]), array([[0.97878192, 0.18457695],
       [0.18457695, 0.97363478]])]
old_w: [0.29839348398925547, 0.20595965236491348, 0.49564686364583294]
performing maximization for iteration:27
new mu: [array([[7.02185423, 4.01561902]]), array([[3.04106966, 3.05

new mu: [array([[7.02166564, 4.01551697]]), array([[3.04017804, 3.04986369]]), array([[5.01196223, 7.00167989]])]
new_cov: [array([[0.99023671, 0.50089167],
       [0.50089167, 0.99564107]]), array([[1.02887715, 0.02772925],
       [0.02772925, 3.38746658]]), array([[0.97942857, 0.18497963],
       [0.18497963, 0.974266  ]])]
old_w: [0.2984231021377575, 0.20570860872488378, 0.4958682891373568]
ll_old:-182313.78651623815
ll_new:-182319.15948300314
performing expectation for iteration:36
old mu: [array([[7.02166564, 4.01551697]]), array([[3.04017804, 3.04986369]]), array([[5.01196223, 7.00167989]])]
old_cov: [array([[0.99023671, 0.50089167],
       [0.50089167, 0.99564107]]), array([[1.02887715, 0.02772925],
       [0.02772925, 3.38746658]]), array([[0.97942857, 0.18497963],
       [0.18497963, 0.974266  ]])]
old_w: [0.2984231021377575, 0.20570860872488378, 0.4958682891373568]
performing maximization for iteration:36
new mu: [array([[7.02165297, 4.01551013]]), array([[3.04011842, 3.04969

new mu: [array([[7.02159384, 4.01547817]]), array([[3.03984045, 3.0489058 ]]), array([[5.01179645, 7.00153265]])]
new_cov: [array([[0.99035833, 0.50093841],
       [0.50093841, 0.99564632]]), array([[1.02861659, 0.02709951],
       [0.02709951, 3.38553451]]), array([[0.97963052, 0.18510591],
       [0.18510591, 0.9744633 ]])]
old_w: [0.2984324066239887, 0.2056303255802452, 0.49593726779576636]
ll_old:-182344.2379291164
ll_new:-182345.91265800234
performing expectation for iteration:45
old mu: [array([[7.02159384, 4.01547817]]), array([[3.03984045, 3.0489058 ]]), array([[5.01179645, 7.00153265]])]
old_cov: [array([[0.99035833, 0.50093841],
       [0.50093841, 0.99564632]]), array([[1.02861659, 0.02709951],
       [0.02709951, 3.38553451]]), array([[0.97963052, 0.18510591],
       [0.18510591, 0.9744633 ]])]
old_w: [0.2984324066239887, 0.2056303255802452, 0.49593726779576636]
performing maximization for iteration:45
new mu: [array([[7.0215899 , 4.01547604]]), array([[3.0398219 , 3.048853

new mu: [array([[7.02157148, 4.01546609]]), array([[3.03973549, 3.04860804]]), array([[5.0117449 , 7.00148683]])]
new_cov: [array([[0.99039621, 0.50095298],
       [0.50095298, 0.99564798]]), array([[1.02853557, 0.02690387],
       [0.02690387, 3.38493418]]), array([[0.97969335, 0.18514524],
       [0.18514524, 0.9745247 ]])]
old_w: [0.29843530497677234, 0.20560598613584988, 0.4959587088873758]
ll_old:-182353.71857970936
ll_new:-182354.23921575389
performing expectation for iteration:54
old mu: [array([[7.02157148, 4.01546609]]), array([[3.03973549, 3.04860804]]), array([[5.0117449 , 7.00148683]])]
old_cov: [array([[0.99039621, 0.50095298],
       [0.50095298, 0.99564798]]), array([[1.02853557, 0.02690387],
       [0.02690387, 3.38493418]]), array([[0.97969335, 0.18514524],
       [0.18514524, 0.9745247 ]])]
old_w: [0.29843530497677234, 0.20560598613584988, 0.4959587088873758]
performing maximization for iteration:54
new mu: [array([[7.02157026, 4.01546543]]), array([[3.03972973, 3.048

new mu: [array([[7.02156454, 4.01546234]]), array([[3.03970289, 3.04851555]]), array([[5.01172888, 7.0014726 ]])]
new_cov: [array([[0.99040799, 0.50095751],
       [0.50095751, 0.9956485 ]]), array([[1.02851041, 0.02684312],
       [0.02684312, 3.38474773]]), array([[0.97971287, 0.18515747],
       [0.18515747, 0.97454377]])]
old_w: [0.2984362057808979, 0.2055984254424416, 0.49596536877666186]
ll_old:-182356.66484878337
ll_new:-182356.8265709443
performing expectation for iteration:63
old mu: [array([[7.02156454, 4.01546234]]), array([[3.03970289, 3.04851555]]), array([[5.01172888, 7.0014726 ]])]
old_cov: [array([[0.99040799, 0.50095751],
       [0.50095751, 0.9956485 ]]), array([[1.02851041, 0.02684312],
       [0.02684312, 3.38474773]]), array([[0.97971287, 0.18515747],
       [0.18515747, 0.97454377]])]
old_w: [0.2984362057808979, 0.2055984254424416, 0.49596536877666186]
performing maximization for iteration:63
new mu: [array([[7.02156415, 4.01546213]]), array([[3.0397011 , 3.048510

new mu: [array([[7.02156238, 4.01546117]]), array([[3.03969276, 3.04848682]]), array([[5.01172391, 7.00146818]])]
new_cov: [array([[0.99041165, 0.50095892],
       [0.50095892, 0.99564866]]), array([[1.02850259, 0.02682425],
       [0.02682425, 3.38468983]]), array([[0.97971893, 0.18516126],
       [0.18516126, 0.9745497 ]])]
old_w: [0.2984364855677754, 0.20559607747578976, 0.49596743695643525]
ll_old:-182357.57992987108
ll_new:-182357.63015199197
performing expectation for iteration:72
old mu: [array([[7.02156238, 4.01546117]]), array([[3.03969276, 3.04848682]]), array([[5.01172391, 7.00146818]])]
old_cov: [array([[0.99041165, 0.50095892],
       [0.50095892, 0.99564866]]), array([[1.02850259, 0.02682425],
       [0.02682425, 3.38468983]]), array([[0.97971893, 0.18516126],
       [0.18516126, 0.9745497 ]])]
old_w: [0.2984364855677754, 0.20559607747578976, 0.49596743695643525]
performing maximization for iteration:72
new mu: [array([[7.02156226, 4.01546111]]), array([[3.0396922 , 3.048

new mu: [array([[7.02156171, 4.01546081]]), array([[3.03968962, 3.0484779 ]]), array([[5.01172236, 7.0014668 ]])]
new_cov: [array([[0.99041278, 0.50095936],
       [0.50095936, 0.99564871]]), array([[1.02850016, 0.02681839],
       [0.02681839, 3.38467185]]), array([[0.97972081, 0.18516244],
       [0.18516244, 0.97455154]])]
old_w: [0.29843657245187716, 0.20559534837945953, 0.49596807916866]
ll_old:-182357.8640946198
ll_new:-182357.879689667
performing expectation for iteration:81
old mu: [array([[7.02156171, 4.01546081]]), array([[3.03968962, 3.0484779 ]]), array([[5.01172236, 7.0014668 ]])]
old_cov: [array([[0.99041278, 0.50095936],
       [0.50095936, 0.99564871]]), array([[1.02850016, 0.02681839],
       [0.02681839, 3.38467185]]), array([[0.97972081, 0.18516244],
       [0.18516244, 0.97455154]])]
old_w: [0.29843657245187716, 0.20559534837945953, 0.49596807916866]
performing maximization for iteration:81
new mu: [array([[7.02156167, 4.01546079]]), array([[3.03968944, 3.04847741]]

new mu: [array([[7.0215615, 4.0154607]]), array([[3.03968864, 3.04847513]]), array([[5.01172189, 7.00146638]])]
new_cov: [array([[0.99041313, 0.50095949],
       [0.50095949, 0.99564873]]), array([[1.02849941, 0.02681658],
       [0.02681658, 3.38466627]]), array([[0.9797214 , 0.18516281],
       [0.18516281, 0.97455211]])]
old_w: [0.29843659943100004, 0.20559512198472002, 0.49596827858427894]
ll_old:-182357.95233292
ll_new:-182357.95717539737
performing expectation for iteration:90
old mu: [array([[7.0215615, 4.0154607]]), array([[3.03968864, 3.04847513]]), array([[5.01172189, 7.00146638]])]
old_cov: [array([[0.99041313, 0.50095949],
       [0.50095949, 0.99564873]]), array([[1.02849941, 0.02681658],
       [0.02681658, 3.38466627]]), array([[0.9797214 , 0.18516281],
       [0.18516281, 0.97455211]])]
old_w: [0.29843659943100004, 0.20559512198472002, 0.49596827858427894]
performing maximization for iteration:90
new mu: [array([[7.02156149, 4.01546069]]), array([[3.03968859, 3.04847498

new mu: [array([[7.02156143, 4.01546066]]), array([[3.03968834, 3.04847427]]), array([[5.01172174, 7.00146624]])]
new_cov: [array([[0.99041324, 0.50095953],
       [0.50095953, 0.99564873]]), array([[1.02849918, 0.02681601],
       [0.02681601, 3.38466454]]), array([[0.97972158, 0.18516292],
       [0.18516292, 0.97455228]])]
old_w: [0.2984366078083639, 0.20559505168653017, 0.4959683405051014]
ll_old:-182357.97973204337
ll_new:-182357.98123568884
performing expectation for iteration:99
old mu: [array([[7.02156143, 4.01546066]]), array([[3.03968834, 3.04847427]]), array([[5.01172174, 7.00146624]])]
old_cov: [array([[0.99041324, 0.50095953],
       [0.50095953, 0.99564873]]), array([[1.02849918, 0.02681601],
       [0.02681601, 3.38466454]]), array([[0.97972158, 0.18516292],
       [0.18516292, 0.97455228]])]
old_w: [0.2984366078083639, 0.20559505168653017, 0.4959683405051014]
performing maximization for iteration:99
new mu: [array([[7.02156143, 4.01546066]]), array([[3.03968832, 3.04847

In [32]:
cov = []
for i in range(2):
    cov.append(np.identity(2))
print(cov)
print([np.identity(2),np.identity(2)])

[array([[1., 0.],
       [0., 1.]]), array([[1., 0.],
       [0., 1.]])]
[array([[1., 0.],
       [0., 1.]]), array([[1., 0.],
       [0., 1.]])]


In [33]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [38]:
me=get_random_mu(2,x_2)
print(me)
print(me[0][0])
print(cov[0])
multivariate_normal.pdf(x_2[0], mean=me[0][0], cov=cov[0])

[array([[6.48522717, 2.36519781]]), array([[3.43149103, 2.75943446]])]
[array([[6.48522717, 2.36519781]]), array([[3.43149103, 2.75943446]])]
[6.48522717 2.36519781]
[[1. 0.]
 [0. 1.]]


0.04477625767438047

In [42]:
a=np.array(x_2[0]-me[0])
print(a)
print(a.T)

[[1.08581649 1.16507636]]
[[1.08581649]
 [1.16507636]]
